function(add_subdirectory_ifdef feature_toggle source_dir)
  if(${${feature_toggle}})
    add_subdirectory(${source_dir})
  endif()
endfunction()

function(add_module_ifdef feature_toggle module_name submodule_name)
  if(${${feature_toggle}})
    target_link_libraries(${module_name} INTERFACE ${submodule_name})
    add_subdirectory(${submodule_name})
  endif()
endfunction()
